export const KEYBOARD_CHARACTERS = {
    firstRow : [
        { onCaps: "`", noCaps: "`", onShift: "~" },
        { onCaps: "1", noCaps: "1", onShift: "!" },
        { onCaps: "2", noCaps: "2", onShift: "@" },
        { onCaps: "3", noCaps: "3", onShift: "#" },
        { onCaps: "4", noCaps: "4", onShift: "$" },
        { onCaps: "5", noCaps: "5", onShift: "%" },
        { onCaps: "6", noCaps: "6", onShift: "^" },
        { onCaps: "7", noCaps: "7", onShift: "&" },
        { onCaps: "8", noCaps: "8", onShift: "*" },
        { onCaps: "9", noCaps: "9", onShift: "(" },
        { onCaps: "0", noCaps: "0", onShift: ")" },
        { onCaps: "-", noCaps: "-", onShift: "_" },
        { onCaps: "=", noCaps: "=", onShift: "+" },
    ],
    secondRow: [
        { onCaps: "Q", noCaps: "q", onShift: "Q" },
        { onCaps: "W", noCaps: "w", onShift: "W" },
        { onCaps: "E", noCaps: "e", onShift: "E" },
        { onCaps: "R", noCaps: "r", onShift: "R" },
        { onCaps: "T", noCaps: "t", onShift: "T" },
        { onCaps: "Y", noCaps: "y", onShift: "Y" },
        { onCaps: "U", noCaps: "u", onShift: "U" },
        { onCaps: "I", noCaps: "i", onShift: "I" },
        { onCaps: "O", noCaps: "o", onShift: "O" },
        { onCaps: "P", noCaps: "p", onShift: "P" },
        { onCaps: "[", noCaps: "[", onShift: "{" },
        { onCaps: "]", noCaps: "]", onShift: "}" },
        { onCaps: "\\", noCaps: "\\", onShift: "|" },
    ],
    thirdRow: [
        { onCaps: "A", noCaps: "a", onShift: "A" },
        { onCaps: "S", noCaps: "s", onShift: "S" },
        { onCaps: "D", noCaps: "d", onShift: "D" },
        { onCaps: "F", noCaps: "f", onShift: "F" },
        { onCaps: "G", noCaps: "g", onShift: "G" },
        { onCaps: "H", noCaps: "h", onShift: "H" },
        { onCaps: "J", noCaps: "j", onShift: "J" },
        { onCaps: "K", noCaps: "k", onShift: "K" },
        { onCaps: "L", noCaps: "l", onShift: "L" },
        { onCaps: ";", noCaps: ";", onShift: ":" },
        { onCaps: "'", noCaps: "'", onShift: '"' },
    ],
    fourthRow: [
        { onCaps: "Z", noCaps: "z", onShift: "Z" },
        { onCaps: "X", noCaps: "x", onShift: "X" },
        { onCaps: "C", noCaps: "c", onShift: "C" },
        { onCaps: "V", noCaps: "v", onShift: "V" },
        { onCaps: "B", noCaps: "b", onShift: "B" },
        { onCaps: "N", noCaps: "n", onShift: "N" },
        { onCaps: "M", noCaps: "m", onShift: "M" },
        { onCaps: ",", noCaps: ",", onShift: "<" },
        { onCaps: ".", noCaps: ".", onShift: ">" },
        { onCaps: "/", noCaps: "/", onShift: "?" },
    ]
}